export enum EtatQuestion {
  START_QUESTION = 'START_QUESTION',
  IMAGE_AFFICHEE = 'IMAGE_AFFICHEE',
  QUESTION_AFFICHEE = 'QUESTION_AFFICHEE',
  REPONSE_DONNEE = 'REPONSE_DONNEE',
  REPONSE_REVELEE = 'REPONSE_REVELEE',
}
